export const LOAD_CUSTOMERS_REQUEST = 'customers/LOAD_CUSTOMERS_REQUEST';
export const LOAD_CUSTOMERS_SUCCESS = 'customers/LOAD_CUSTOMERS_SUCCESS';

export const CREATE_CUSTOMER_REQUEST = 'customers/CREATE_CUSTOMER_REQUEST';
